//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAppGestor.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public class GestorDeAppsEntities //: DbContext
    {
        public GestorDeAppsEntities()
            //: base("name=GestorDeAppsEntities")
        {
            data = new StaticData();
            PROGRAMAs = data.Programas;
            CATEGORIAs = data.Categorias;
        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        //public virtual DbSet<CATEGORIA> CATEGORIAs { get; set; }
        //public virtual DbSet<PROGRAMA> PROGRAMAs { get; set; }

        public StaticData data;
        public List<PROGRAMA> PROGRAMAs;
        public List<CATEGORIA> CATEGORIAs;

    }
}
