//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAppGestor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA
    {
        public int CODIGO { get; set; }
        public Nullable<int> CODIGOCAT { get; set; }
        public string NOMBRE { get; set; }
        public string PLATAFORMA { get; set; }
        public string VERSION { get; set; }
        public Nullable<int> DESCARGAS { get; set; }
        public string HOST { get; set; }
        public Nullable<bool> INSTALADO { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
